catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

patchedDependencies:
  unishox2.siara.cc@1.1.5: patches/unishox2.siara.cc@1.1.5.patch

catalogs:
  dev:
    '@types/node': ^24.10.13
    '@types/pako': ^2.0.4
    '@ycs77/eslint-config': ^7.0.0
    bumpp: ^10.4.1
    eslint: ^9.39.2
    n8n-workflow: ^1.120.8
    npm-run-all2: ^8.0.4
    tsdown: ^0.18.4
    tsx: ^4.21.0
    typescript: ~5.9.3
    unishox2.siara.cc: ^1.1.5
    vitest: ^4.0.18
  prod:
    '@clack/prompts': ^0.11.0
    '@modelcontextprotocol/sdk': ^1.26.0
    cac: ^6.7.14
    js-crypto-aes: ^1.0.6
    js-crypto-hash: ^1.0.7
    pako: ^2.1.0
    picocolors: ^1.1.1
    zod: ^4.3.6

onlyBuiltDependencies:
  - esbuild
